DEFAULT_PRESSURE = 40
DEFAULT_POPULATION_THRESHOLD = 100
DEFAULT_WSA_THRESHOLD = 0.8
DEFAULT_SIM_DURATION_HOURS = 24

# For REV CITY ZONE

REV_CITY_ZONE_LEAK_FACTOR=1.4
REV_CITY_ZONE_AGING_FACTOR=0.8
REV_CITY_ZONE_REQUIRED_PRESSURE=30.5
REV_CITY_ZONE_MAX_PUMPS=5
REV_CITY_ZONE_LOOP_COUNT=5
REV_CITY_ZONE_MAX_TANKS=5


RURAL_SIMPLE_LEAK_FACTOR=1.05
RURAL_SIMPLE_AGING_FACTOR=0.95
RURAL_SIMPLE_REQUIRED_PRESSURE=31.5
RURAL_SIMPLE_MAX_PUMPS=2
RURAL_SIMPLE_LOOP_COUNT=0
RURAL_SIMPLE_MAX_TANKS=0


REV_SIMPLE_LEAK_FACTOR=1.05
REV_SIMPLE_AGING_FACTOR=0.95
REV_SIMPLE_REQUIRED_PRESSURE=24.7
REV_SIMPLE_MAX_PUMPS=2
REV_SIMPLE_LOOP_COUNT=2
REV_SIMPLE_MAX_TANKS=1

